-- Compatibilidade da tabela EMAIL_CAMPAIGN já existente.
-- O bloco é idempotente: ignora ORA-01430 quando a coluna já existe.

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_CAMPAIGN ADD (INTERNAL_NAME VARCHAR2(255))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_CAMPAIGN ADD (REPLY_TO VARCHAR2(255))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

COMMIT;
