DEPLOY_REMOTE_HOST=ubuntu@52.67.135.170
DEPLOY_SSH_KEY=/home/daniel/Code/infra/amazon-infra/ec2/52.67.135.170/core/inatto01-sp.pem
DEPLOY_REMOTE_ROOT=/home/ubuntu/apps/orbital/orbital-mail
DEPLOY_API_PORT=8104
DEPLOY_WEB_PORT=4104
DEPLOY_API_SERVICE=orbital-mail-api.service
DEPLOY_WEB_SERVICE=orbital-mail-web.service
DEPLOY_PUBLIC_URL=https://email.anpprev.org
DEPLOY_ORBITAL_URL=https://admin.anpprev.org
