# Destino remoto do orbital-mail.
DEPLOY_REMOTE_HOST=ubuntu@52.67.135.170
DEPLOY_SSH_KEY=/home/daniel/Code/infra/amazon-infra/ec2/52.67.135.170/core/inatto01-sp.pem
DEPLOY_REMOTE_ROOT=/home/ubuntu/apps/orgs/orbital/orbital-mail
